// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultHeader: typeof import('./../components/layout/DefaultHeader.vue')['default']
    FatalErrorViewer: typeof import('./../components/layout/FatalErrorViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./../components/template.vue')['default']
    Toast: typeof import('./../components/layout/Toast.vue')['default']
    WorkInProgress: typeof import('./../components/generic/WorkInProgress.vue')['default']
  }
}
